### ISSUE TITLE
Error on Connect

### ISSUE THREAD

**Issue by kaischallenberg** [techchrism/valorant-websocket-logger#1]
Hey, 

I'm testing out your package and encountered the following error:

When trying to connect to the local websocket, the connection is rejected. I also tried the whole thing myself with a WebSocket client and encountered the same error. 

Do you know what could be the reason for this?

![image](https://user-images.githubusercontent.com/26031319/177881555-6ce6394c-609a-4b2b-a402-2a3c72f734a9.png)

**Comment by techchrism** [comment]
I was able to replicate this issue with Node v17.0.1
Version 16.13.1 (and probably all others in 16) still works as expected

**Comment by techchrism** [comment]
It should now work in newer Node versions
